// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}
